export const chainIdMap = {
  "0x1": "Ethereum Mainnet",
  "0x5": "Goerli Testnet",
  "0xaa36a7": "Sepolia Testnet",
  "0x89": "Polygon Mainnet",
  "0x13881": "Mumbai Testnet",
  "0xa": "Optimism",
  "0x66eed": "Arbitrum Testnet",
  "0x144": "Blast Sepolia",
};

export const READ_RPC_URLS = [
  "https://rpc.ankr.com/eth_sepolia",
  "https://ethereum-sepolia.publicnode.com",
  "https://sepolia.drpc.org",
];

export const API_ORIGIN = "";

export const factoryAddress = "0xcad3994c714a1812b7f265458791a682eced33c8";

export const factoryAbi = [
  "error EmptyArgs()",
  "error EmptySecrets()",
  "error EmptySource()",
  "error GitbountyFactory__SendNonZeroEth()",
  "error GitbountyFactory__UsernameAlreadyMapped()",
  "error InvalidBatchSize(uint256 size, uint256 maxAllowed)",
  "error InvalidBounty(address bounty)",
  "error NoBounties()",
  "error NoInlineSecrets()",
  "error NotRegisteredBounty(address bounty)",
  "error OnlyRouterCanFulfill()",
  "error OnlySelf()",
  "error UnknownRequest(bytes32 requestId)",
  "error UsernameRequired()",
  "event BountyClosed(address indexed bounty)",
  "event BountyDeployed(address indexed bounty, address indexed bountyOwner)",
  "event BountyOpened(address indexed bounty)",
  "event BountyRegistered(address indexed bounty)",
  "event FactoryConfigUpdated(bytes32 donID, uint64 subId, uint32 callbackGasLimit)",
  "event FunctionsRequestFailed(address indexed bounty, string reason, bytes lowLevelData)",
  "event GithubUserMapped(string indexed username, address indexed userAddress)",
  "event ManualUpkeepSkipped(address indexed bounty, string reason)",
  "event ManualUpkeepTriggered(address indexed bounty, address indexed caller, bytes32 indexed requestId)",
  "event OwnershipTransferRequested(address indexed from, address indexed to)",
  "event OwnershipTransferred(address indexed from, address indexed to)",
  "event RequestForwarded(bytes32 indexed requestId, address indexed bounty)",
  "event RequestFulfilled(bytes32 indexed id)",
  "event RequestSent(bytes32 indexed requestId, address indexed bounty)",
  "event RequestSent(bytes32 indexed id)",
  "event SecretsUpdated()",
  "event SourceUpdated()",
  "event UpkeepSelected(uint256 indexed at, address[] selected)",
  "function _sendFunctionsRequestExternal(string[] args) returns (bytes32)",
  "function acceptOwnership()",
  "function adminUnlockBounty(address bounty)",
  "function bounties(uint256) view returns (address)",
  "function bountyCount() view returns (uint256)",
  "function callbackGasLimit() view returns (uint32)",
  "function checkUpkeep(bytes) view returns (bool upkeepNeeded, bytes performData)",
  "function closeBounty(address bounty)",
  "function createBounty(string _repoOwner, string _repo, string _issueNumber) payable returns (address bountyAddr)",
  "function donID() view returns (bytes32)",
  "function eligibilityBreakdown(address bounty) view returns ( bool registered, bool open, bool notInFlight, bool timeOk, bool childReady, uint256 nextAt, bool manualTimeOk, uint256 nextManualAt )",
  "function encryptedSecretsUrls() view returns (bytes)",
  "function functionsSubId() view returns (uint64)",
  "function getAddressFromUsername(string username) view returns (address)",
  "function getAutomationParams() view returns (uint256 retryInterval_, uint256 maxScan_, uint256 maxPerform_, uint256 manualRetryInterval_)",
  "function getBounties(uint256 start, uint256 limit) view returns (address[] bountyAddresses, uint256[] nextAttemptAts)",
  "function handleOracleFulfillment(bytes32 requestId, bytes response, bytes err)",
  "function implementation() view returns (address)",
  "function inFlight(address) view returns (bool)",
  "function isEligible(address bounty) view returns (bool eligible)",
  "function isEligibleManual(address bounty) view returns (bool eligible)",
  "function lastRequestForBounty(address) view returns (bytes32)",
  "function manualPerformUpkeep(address[] selected)",
  "function manualRetryInterval() view returns (uint256)",
  "function mapGithubUsernameToAddress(string username)",
  "function openBounty(address bounty)",
  "function owner() view returns (address)",
  "function performUpkeep(bytes performData)",
  "function registerBounty(address bounty)",
  "function requestToBounty(bytes32) view returns (address)",
  "function resetGithubUserMapping()",
  "function setAutomationParams(uint256 _retryInterval, uint256 _maxScan, uint256 _maxPerform)",
  "function setFunctionsConfig(bytes32 _donID, uint64 _subId, uint32 _callbackGasLimit)",
  "function setManualRetryInterval(uint256 _manualRetryInterval)",
  "function setSecrets(bytes newEncryptedSecretsUrls)",
  "function setSource(string newSource)",
  "function source() view returns (string)",
  "function transferOwnership(address to)"
];

const _bountyAbiRaw = [
  "error Gitbounty__AlreadyInitialized()",
  "error Gitbounty__CriteriaNotSet()",
  "error Gitbounty__NoFundToWithdraw()",
  "error Gitbounty__NotOpen()",
  "error Gitbounty__NotOwner()",
  "error Gitbounty__OnlyFactory()",
  "error Gitbounty__SendNonZeroEth()",
  "error Gitbounty__TransferFailed()",
  "error Gitbounty__UnexpectedRequestID(bytes32 requestId)",
  "event BountyClaimed(address indexed winner, uint256 value)",
  "event BountyFundWithdrawn(address indexed sender, uint256 value)",
  "event BountyFunded(address indexed sender, uint256 value)",
  "event Response(bytes32 indexed requestId, bytes response, bytes err)",
  "function abandonInFlight()",
  "function createAndFundBounty(string _owner, string _repo, string _issue) payable",
  "function deleteAndRefundBounty()",
  "function factory() view returns (address)",
  "function fundBounty() payable",
  "function getArgs() view returns (string _repo_owner, string _repo, string _issueNumber)",
  "function getBalance() view returns (uint256)",
  "function getBountySnapshot() view returns (Gitbounty.BountySnapshot s)",
  "function getContribution() view returns (uint256)",
  "function getFunderCount() view returns (uint256)",
  "function getGitbountyState() view returns (Gitbounty.GitbountyState)",
  "function getIssueNumber() view returns (string)",
  "function getLastResponse() view returns (bytes)",
  "function getRepo() view returns (string)",
  "function getRepoOwner() view returns (string)",
  "function initialise(address _owner, string _repoOwner, string _repo, string _issueNumber) payable",
  "function isBountyReady() view returns (bool)",
  "function lastWinnerUser() view returns (string)",
  "function last_BountyAmount() view returns (uint256)",
  "function last_issueNumber() view returns (string)",
  "function last_repo() view returns (string)",
  "function last_repo_owner() view returns (string)",
  "function markCalculating(bytes32 requestId)",
  "function onFunctionsFulfilled(bytes32 requestId, address winner, bytes response, bytes err)",
  "function owner() view returns (address)",
  "function refundAllFunders()",
  "function resetContract()",
  "function s_lastError() view returns (bytes)",
  "function s_lastRequestId() view returns (bytes32)",
  "function s_lastResponse() view returns (bytes)",
  "function setBountyCriteria(string _owner, string _repo, string _issue)",
  "function withdrawBountyFund()",
  "function withdrawPartialBountyFund(uint256 amount)"
];

// Struct/enum return types can't be auto-extracted via cast interface — hardcoded here
export const bountyAbi = [
  ..._bountyAbiRaw.filter(e => !e.includes("getBountySnapshot") && !e.includes("getGitbountyState")),
  "function getBountySnapshot() view returns (tuple(uint8 state, address owner, address factory, bool initialized, string repoOwner, string repo, string issueNumber, uint256 totalFunding, uint256 funderCount, address lastWinner, string lastWinnerUser, string last_repo_owner, string last_repo, string last_issueNumber, uint256 lastBountyAmount) s)",
  "function getGitbountyState() view returns (uint8)",
];