[profile.default]
src = "src"
out = "out"
optimizer = true
optimizer_runs = 1
via_ir = true
ffi = true
libs = ["lib"]
remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "@chainlink/v1/=lib/chainlink/contracts/src/v0.8/functions/dev/v1_X/",
    "@chainlink/=lib/chainlink/",
    "@solmate=lib/solmate/src",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
    { access = "read", path = "./script.js" },
    { access = "read", path = "./offchain" },
    { access = "read", path = "./config" },
]

[fuzz]
runs = 256
